### ISSUE TITLE
Donner la possiblité de voir tous les dossiers dans une seule couche

### ISSUE THREAD

**Issue by SOGEFI** [Gustry/GeoFoncier-consultation#15]
Donner la possibilité de voir tous les dossiers dans une seule couche (un seule couche localisant et une seul couche polygone d'emprise)

**Comment by Gustry** [comment]
Le plugin gère déjà que 2 couches, pour l'ensemble des dossiers.
Le seul problème se pose si tu ferme la fenêtre et que tu es obligé de re-renseigner ton login/password, est-ce que cas la dont tu parle ?

**Comment by SOGEFI** [comment]
oui ça doit être ça.

Dit autrement il faufdrait s'assurer qu'il n'y ait toujours qu'une seule couche "Dossiers GéoFoncier (localisants)" et qu'une seule couche "Dossiers GéoFoncier (emprises)" dans l'arbre des couches.

Idéalement même, la couche "Dossiers GéoFoncier (emprises)" ne devrait apparaitre que si il existe au moins 1 polygone d'emprise.

**Comment by Gustry** [comment]
Concernant la multiplicité des couches, ce problème a été normalement résolu pour le passage lors du changement de l'IHM.
