### ISSUE TITLE
Rajouter un lien pour récupérer l'archive ZIP d'un dossier

### ISSUE THREAD

**Issue by SOGEFI** [Gustry/GeoFoncier-consultation#16]
Rajouter un lien pour récupérer l'archive ZIP d'un dossier dans la table attributaire des dossiers chargés

**Comment by Gustry** [comment]
Si on parle bien de la table attributaire de la couche, alors j'ai rajouté le lien sous forme textuelle de l'archive ZIP. Je ne peux pas rajouter un bouton dans cette table.
Les boutons pour les archives zip sont déjà présent dans les 2 onglets "Dossiers" et "Détails" du plugin.
C'était bien çà ?
