### ISSUE TITLE
Utiliser un volet bas plutôt qu'une fenêtre

### ISSUE THREAD

**Issue by SOGEFI** [Gustry/GeoFoncier-consultation#17]
Ne vaudrait-il pas mieux utiliser un volet bas plutôt qu'une fenêtre ??

**Comment by Gustry** [comment]
Tout à fait ! Je me suis posé la question aussi. Si on ferme la fenêtre, on est obligé de re-télécharger l'ensemble des dossiers.
Mais cela oblige une petite refonte de l'IHM. Afficher globalement la même fenêtre dans un dock horizontal en bas ? Donc en perdant de l'espace sur l'arbre des couches et l'espace carto ?
