### ISSUE TITLE
Proposer la couche "Bing aerial" en plus de OSM

### ISSUE THREAD

**Issue by SOGEFI** [Gustry/GeoFoncier-consultation#23]
Proposer la couche "Bing aerial" en plus de OSM (les gens aiment bien la photo aérienne).
Libellé du nom de la couche "Photo aérienne Bing"

**Comment by Gustry** [comment]
Totalement d'accord, mais si tu as un fichier VRT type https://github.com/Gustry/GeoFoncier-consultation/blob/master/resources/osmfr.xml je suis preneur. Car j'ai pas trouvé les options pour le moment.

**Comment by Gustry** [comment]
Je ferme, sauf si tu tiens à Bing au lieu de Google.
