### ISSUE TITLE
Impossible d'ouvrir le fichier zip via le bouton "Ouvrir le fichier"

### ISSUE THREAD

**Issue by SOGEFI** [Gustry/GeoFoncier-consultation#25]
Impossible d'ouvrir le fichier zip via le bouton "Ouvrir le fichier" (problème d'encodage de la référence dossier dans le nom du fichier zip qui est enregistré".

Tester avec dossier "Étienne 2013"

**Comment by Gustry** [comment]
- remplacement d'un caractère accentué par l'équivalent non accentué
- remplacement des espaces par des tirets
