### ISSUE TITLE
Éviter de retélécharger un document déjà téléchargé

### ISSUE THREAD

**Issue by Gustry** [Gustry/GeoFoncier-consultation#28]

**Comment by SOGEFI** [comment]
A éviter à mon avis. Car le principe d'une API est d’accéder en permanence aux données les plus fraîches...le document pourrait tout à fait avoir été supprimé du dossier par le GE (exemple errreur dans le document...).

Cela rejoins ma demande pour pouvoir recharger à tout moment la liste des dossiers (exemple le GE à un client au téléphone " vous voyez le nouveau plan de bornage que je vous est mis à disposition ?")

**Comment by Gustry** [comment]
Ce ticket était pour éviter de retélécharger un document si l'utilisateur vient juste de fermer le fenêtre de visualisation du document. La connexion internet est obligatoire à chaque ouverture de document.
Si le ticket ne convient pas tu peux le mettre en invalide et le fermer.
