### ISSUE TITLE
Faire en sorte que les documents puisse s'ouvrir sans passer par un navigateur et sans avoir à saisir à nouveau les codes d'accès

### ISSUE THREAD

**Issue by SOGEFI** [Gustry/GeoFoncier-consultation#4]
Faire en sorte que les documents puisse s'ouvrir sans passer par un navigateur et sans avoir à saisir à nouveau les codes d’accès

**Comment by Gustry** [comment]
- Meilleure solution : Afficher les documents entièrement à l'intérieur du plugun qgis
- Autre solution : Pouvoir passer les codes d'accès directement au navigateur : http://stackoverflow.com/questions/19960426/https-authentification-with-qdesktopservices-and-qurl
