### ISSUE TITLE
Pas d'animation de la barre de chargement

### ISSUE THREAD

**Issue by Gustry** [Gustry/GeoFoncier-consultation#9]
Sous Kubuntu, pas d'animation.
A vérifier sur les autres OS.
Test de @SOGEFI ?

**Comment by SOGEFI** [comment]
Pas d'animation non plus sous Win 8 ! ça semble être généralisé...

**Comment by Gustry** [comment]
A faire, gestion d'erreur sur un fichier, ou annulation de la part des utilisateurs

**Comment by Gustry** [comment]
Ce n'est plus d'actualité, je clos.
